// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1L1rtMUjPrJfEYI6Ph15g6y-1tikx1dk',
    appId: '1:1091623739941:web:0628d743b2a2294947d5cc',
    messagingSenderId: '1091623739941',
    projectId: 'flutter-book-review-616ee',
    authDomain: 'flutter-book-review-616ee.firebaseapp.com',
    storageBucket: 'flutter-book-review-616ee.appspot.com',
    measurementId: 'G-N9KZGYQ1VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDkusoIeYmzQVyEUpz3Gi3WjFtqfyGYg',
    appId: '1:1091623739941:android:f98866720dceaa6347d5cc',
    messagingSenderId: '1091623739941',
    projectId: 'flutter-book-review-616ee',
    storageBucket: 'flutter-book-review-616ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpF_L1mgfxBfhcvXh3TruyR-zh2I99lI',
    appId: '1:1091623739941:ios:9fc95ba7446659bc47d5cc',
    messagingSenderId: '1091623739941',
    projectId: 'flutter-book-review-616ee',
    storageBucket: 'flutter-book-review-616ee.appspot.com',
    iosBundleId: 'com.example.bookReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpF_L1mgfxBfhcvXh3TruyR-zh2I99lI',
    appId: '1:1091623739941:ios:a750654f70fd499547d5cc',
    messagingSenderId: '1091623739941',
    projectId: 'flutter-book-review-616ee',
    storageBucket: 'flutter-book-review-616ee.appspot.com',
    iosBundleId: 'com.example.bookReview.RunnerTests',
  );
}
